# .github/workflows/deploy.yml
name: Deploy to GitHub Pages

on:
    push:
        branches:
            - main # mainブランチ更新時に実行

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            # 1. リポジトリをチェックアウト（完全履歴を取得）
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            # 2. Node.js をセットアップ
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 18

            # 3. 依存関係をインストール
            - name: Install dependencies
              run: npm ci

            # 4. ビルドを実行
            - name: Build project
              run: npm run build

            # 5. GitHub Pages へデプロイ
            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v4
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./dist # Viteのデフォルトビルド出力ディレクトリ
